### ISSUE TITLE
How do you create a subscription that ends on a fixed date?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#218] opened 2015-06-02 19:39 UTC
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

[:octocat: View Markdown File](https://github.com/websharks/s2member-kb/blob/master/questions/2015/218-how-do-you-create-a-subscription-that-ends-on-a-fixed-date.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/s2member-kb/edit/master/questions/2015/218-how-do-you-create-a-subscription-that-ends-on-a-fixed-date.md)
:page_with_curl: **Published KB Article:** http://s2member.com/kb-article/how-do-you-create-a-subscription-that-ends-on-a-fixed-date/

---

**Comment by patdumond** [comment] 2015-06-03 16:23
A user wanted to know how to create a subscription that ended on a fixed date. I created a ProForm page that sold a subscription ending on *31 October 2015*.

Note: You must use a plugin such as [ezPHP](https://wordpress.org/plugins/ezphp/) to use PHP codes in your s2Member forms. Please see this [s2Member KB article](https://s2member.com/kb-article/ezphp-for-wordpress/). **I use ezPHP which allows me to use the `[php]...[/php]` shortcodes used below. Not all PHP plugins allow you to use a shortcode.**

Use this PHP code on your page to assign the EOT date (it must be placed before the form shortcode -- I put mine at the top of the page):

```
[php]

$now = strtotime("now");

$fixed_time = strtotime("31 October 2015");

$days_until_fixed_time = round(($fixed_time - $now) / ($seconds_in_one_day = 86400));

[/php]

```

Create a proforms shortcode using the s2Member control panel:

`[s2Member-Pro-PayPal-Form level="1" ccaps="" desc="$0.01 USD / One Time (for 1 year access, non-recurring)" ps="paypal" lc="" cc="USD" dg="0" ns="1" custom="pat.websharks-inc.net" ta="0" tp="0" tt="D" ra="0.01" rp="[php]echo $days_until_fixed_time;[/php]" rt="D" rr="0" rrt="" rra="2" accept="paypal,visa,mastercard,amex" accept_via_paypal="paypal" coupon="" accept_coupons="0" default_country_code="" captcha="0" /]`


You will need to change the following attributes in your shortcode:

`desc` - I did not change mine because it was for testing. Yours could look something like this: `desc="$25.00 USD / One Time (Unlimited Access Until 31 October 2015)"`

`rp` - Replace the `rp` value with the following php code `[php]echo $days_until_fixed_time;[/php]`

`rt` - Make sure **rt="D"**. I left mine at "Y" for my first test and that user had a 150 year subscription.

**Comment by jaswsinc** [comment] 2015-06-03 17:21
@patdumond Nice work. I converted your example to a KB article in the leading comment above ↑. Please review when you get a moment and we can correct any problems before this is published.

**Comment by raamdev** [comment] 2015-06-03 17:56
@jaswsinc @patdumond are you aware of these existing KB Articles related to this?

- [Specifying a future start date for a recurring subscription (aka Custom EOT)](http://s2member.com/kb-article/specifying-a-future-start-date-for-a-recurring-subscription-aka-custom-eot/)
- [How can I offer a fixed-term Free Registration?](http://s2member.com/kb-article/how-can-i-offer-a-fixed-term-free-registration/)

If this is not a duplicate of one of these (it doesn't appear to be--I think it's a _slightly_ different scenario), you may want to link to both of those at the bottom of this KB Article ("See Also:").

**Comment by patdumond** [comment] 2015-06-03 19:32
Jason,

The only thing that jumped out at me is that you said "you will need to enter this in the HTML tab of the WordPress editor" and it is actually labeled as "Text".  Raam is right. This is not the same situation described in those KB articles, but is related, so a link to those articles would not be out of place.  

I'll use this article as an example for the next time I need to write one, so it will be more detailed than the comment I left earlier. Closer to a finished product, in other words. Thanks for the opportunity to do this.

**Closed** 2015-06-09 11:55 UTC
Labels: published, questions
